version: '3.8'
services:
    db:
        container_name: 'storefront_db'
        image: 'postgres'
        volumes:
            - ./pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},${POSTGRES_TEST_DB}
        ports:
            - '5432:5432'
